package org.acme.features.market.color.domain.gateway;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import org.acme.features.market.color.domain.model.Color;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class ColorCached {

  /**
   * @autogenerated CachedGenerator
   */
  @NonNull
  private OffsetDateTime since;

  /**
   * the real value
   *
   * @autogenerated CachedGenerator
   */
  @NonNull
  private List<Color> value;

  /**
   * @autogenerated CachedGenerator
   * @return
   */
  public Optional<Color> first() {
    return value.isEmpty() ? Optional.empty() : Optional.of(value.get(0));
  }
}
