package org.acme.features.market.medal.domain.model;

import java.util.Optional;

import org.acme.common.exception.ConstraintException;
import org.acme.common.validation.ConstraintFail;
import org.acme.common.validation.ConstraintFailList;
import org.acme.features.market.medal.domain.model.valueobject.MedalNameVO;
import org.acme.features.market.medal.domain.model.valueobject.MedalUidVO;
import org.acme.features.market.medal.domain.model.valueobject.MedalVersionVO;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;

@Getter
@ToString
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Medal implements MedalRef {

  /**
   * @autogenerated EntityGenerator
   */
  public static class MedalBuilder {

    /**
     * @autogenerated EntityGenerator
     * @return
     */
    public Medal buildValid() {
      ConstraintFailList list = new ConstraintFailList();
      if (null == uid) {
        list.add(new ConstraintFail("REQUIRED", "uid", null));
      }
      if (null == name) {
        list.add(new ConstraintFail("REQUIRED", "name", null));
      }
      if (list.hasErrors()) {
        throw new ConstraintException(list);
      }
      return build();
    }

    /**
     * @autogenerated EntityGenerator
     * @param name
     * @return
     */
    public MedalBuilder nameValue(final String name) {
      return name(MedalNameVO.from(name));
    }

    /**
     * @autogenerated EntityGenerator
     * @param uid
     * @return
     */
    public MedalBuilder uidValue(final String uid) {
      return uid(MedalUidVO.from(uid));
    }

    /**
     * @autogenerated EntityGenerator
     * @param version
     * @return
     */
    public MedalBuilder versionValue(final Integer version) {
      return version(MedalVersionVO.from(version));
    }
  }

  /**
   * El name de medal
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private MedalNameVO name;

  /**
   * A number to identify the db record
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private MedalUidVO uid;

  /**
   * Campo con el número de version de medal para controlar bloqueos optimistas
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  @Builder.Default
  private MedalVersionVO version = MedalVersionVO.empty();

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public String getNameValue() {
    return getName().getValue();
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public String getUidValue() {
    return getUid().getValue();
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public Optional<Integer> getVersionValue() {
    return getVersion().getValue();
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public Medal withEmptyVersion() {
    return withVersion(MedalVersionVO.empty());
  }

  /**
   * @autogenerated EntityGenerator
   * @param name
   * @return
   */
  public Medal withNameValue(final String name) {
    return withName(MedalNameVO.from(name));
  }

  /**
   * @autogenerated EntityGenerator
   * @param uid
   * @return
   */
  public Medal withUidValue(final String uid) {
    return withUid(MedalUidVO.from(uid));
  }

  /**
   * @autogenerated EntityGenerator
   * @param version
   * @return
   */
  public Medal withVersionValue(final Integer version) {
    return withVersion(MedalVersionVO.from(version));
  }

  /**
   * @autogenerated EntityGenerator
   * @param version
   * @return
   */
  public Medal withVersionValue(final Optional<Integer> version) {
    return version.isPresent() ? withVersion(MedalVersionVO.from(version.get()))
        : withEmptyVersion();
  }
}
