package org.acme.features.market.medal.application;

import org.acme.features.market.medal.domain.model.Medal;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class MedalPopulateResult {

  /**
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final MedalDto dto;

  /**
   * @autogenerated EntityGenerator
   */
  private final Medal original;
}
