package org.acme.features.market.color.application.interaction.query;

import java.util.Optional;

import org.acme.common.action.Interaction;
import org.acme.features.market.color.domain.model.ColorRef;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class ColorEntityAllowQuery extends Interaction {

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated EntityGenerator
   */
  private final ColorRef reference;

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public Optional<ColorRef> getReference() {
    return Optional.ofNullable(reference);
  }
}
