package org.acme.features.market.medal.application.usecase.create;

import org.acme.common.action.Interaction;
import org.acme.features.market.medal.application.service.event.MedalEntityEvent;
import org.acme.features.market.medal.domain.model.Medal;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class MedalCreateEvent extends MedalEntityEvent {

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @param emitter
   * @param interaction
   * @param entity
   */
  @SuppressWarnings("unchecked")
  public static void notifyWith(final Event<? extends MedalCreateEvent> emitter,
      final Interaction interaction, final Medal entity) {
    ((Event<MedalCreateEvent>) emitter)
        .fire(MedalCreateEvent.builder().interaction(interaction).entity(entity).build());
  }

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @return
   */
  @Override
  public String operation() {
    return "create";
  }
}
