package org.acme.features.market.medal.application.service.event;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.function.Consumer;

import org.acme.common.action.Interaction;
import org.acme.features.market.medal.application.MedalDto;
import org.acme.features.market.medal.domain.model.Medal;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class MedalFormulaBuilderPipelineStageEvent {

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   */
  @NonNull
  private CompletionStage<MedalDto> dto;

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   */
  private Medal original;

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   * @return
   */
  public Optional<Medal> getOriginal() {
    return Optional.ofNullable(original);
  }

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   * @param mapper
   */
  public void tap(Consumer<MedalDto> mapper) {
    dto = dto.thenApply(dto -> {
      mapper.accept(dto);
      return dto;
    });
  }
}
