package org.acme.features.market.verify.application.usecase.delete;

import java.util.List;

import org.acme.common.batch.stepper.ItemDescriptor;
import org.acme.common.batch.stepper.ItemProcessor;
import org.acme.common.batch.stepper.ItemReader;
import org.acme.common.batch.stepper.ItemWriter;
import org.acme.common.batch.stepper.StepContext;
import org.acme.common.batch.stepper.StepCounter;
import org.acme.common.batch.stepper.StepFinalizer;
import org.acme.common.batch.stepper.StepInitializer;
import org.acme.common.exception.ExecutionException;
import org.acme.common.security.Allow;
import org.acme.features.market.verify.application.service.VerifysVisibilityService;
import org.acme.features.market.verify.domain.gateway.VerifyCursor;
import org.acme.features.market.verify.domain.model.Verify;

import io.quarkus.arc.Unremovable;
import jakarta.enterprise.context.RequestScoped;
import lombok.Data;
import lombok.RequiredArgsConstructor;

@Unremovable
@RequestScoped
@RequiredArgsConstructor
class DeleteVerifysInBatchExecutor implements
    StepCounter<VerifyDeleteAllInBatchCommand, DeleteVerifysInBatchExecutor.VerifyPaginableBatch>,
    StepFinalizer<VerifyDeleteAllInBatchCommand, DeleteVerifysInBatchExecutor.VerifyPaginableBatch>,
    StepInitializer<VerifyDeleteAllInBatchCommand, DeleteVerifysInBatchExecutor.VerifyPaginableBatch>,
    ItemReader<Verify, VerifyDeleteAllInBatchCommand, DeleteVerifysInBatchExecutor.VerifyPaginableBatch>,
    ItemWriter<Verify, VerifyDeleteAllInBatchCommand, DeleteVerifysInBatchExecutor.VerifyPaginableBatch>,
    ItemProcessor<Verify, Verify, VerifyDeleteAllInBatchCommand, DeleteVerifysInBatchExecutor.VerifyPaginableBatch>,
    ItemDescriptor<Verify, VerifyDeleteAllInBatchCommand, DeleteVerifysInBatchExecutor.VerifyPaginableBatch> {

  /**
   * @autogenerated EntityGenerator
   */
  @Data
  public static class VerifyPaginableBatch {

    /**
     * @autogenerated EntityGenerator
     */
    private String since;
  }

  /**
   * @autogenerated EntityGenerator
   */
  private final int size = 10;

  /**
   * @autogenerated EntityGenerator
   */
  private final DeleteVerifyUsecase usecase;

  /**
   * @autogenerated EntityGenerator
   */
  private final VerifysVisibilityService visibility;

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public long approximatedItems(
      final StepContext<VerifyDeleteAllInBatchCommand, VerifyPaginableBatch> context) {
    return visibility.countVisibles(context.getParams(), context.getParams().getFilter());
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void finish(
      final StepContext<VerifyDeleteAllInBatchCommand, VerifyPaginableBatch> context) {
    usecase.flush();
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void init(final StepContext<VerifyDeleteAllInBatchCommand, VerifyPaginableBatch> context) {
    context.setState(new VerifyPaginableBatch());
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public String itemDescription(final Verify item,
      final StepContext<VerifyDeleteAllInBatchCommand, VerifyPaginableBatch> context) {
    return item.getUidValue();
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public Verify process(final Verify item,
      final StepContext<VerifyDeleteAllInBatchCommand, VerifyPaginableBatch> context) {
    Allow allowed = usecase.allow(context.getParams(), item);
    if (!allowed.isAllowed()) {
      throw new ExecutionException("not-allowed", null);
    }
    return item;
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public List<Verify> read(
      final StepContext<VerifyDeleteAllInBatchCommand, VerifyPaginableBatch> context) {
    List<Verify> page =
        visibility.listVisibles(context.getParams(), context.getParams().getFilter(),
            VerifyCursor.builder().limit(size).sinceUid(context.getState().getSince()).build());
    context.getState().setSince(page.isEmpty() ? null : page.get(page.size() - 1).getUidValue());
    return page;
  }

  /**
   * @autogenerated EntityGenerator
   * @param items
   * @param context
   */
  @Override
  public void write(final List<Verify> items,
      final StepContext<VerifyDeleteAllInBatchCommand, VerifyPaginableBatch> context) {
    items.forEach(item -> usecase.delete(context.getParams(), item));
  }
}
