quarkus:
  datasource:
    db-kind: postgresql
    username: test_write
    password: test
    jdbc:
      url: jdbc:postgresql://${datasource.host:localhost}:${datasource.port:5432}/${datasource.path:5432}?currentSchema=${datasource.schema:public}
      max-size: 1
      min-size: 1

app:
  migration:
    db-kind: postgresql
    username: test_write # test_read luego, por ahora test_write
    password: test
    group: pgsql
    location: db/migration/pgsql/changelog.txt
    jdbc:
      url: jdbc:postgresql://${datasource.host:localhost}:${datasource.port:5432}/${datasource.path:5432}?currentSchema=${datasource.schema:public}
  