quarkus:
  datasource:
    db-kind: postgresql
    username: test_write # test_read luego, por ahora test_write
    password: test
    jdbc:
      # url: jdbc:postgresql://localhost:${datasource.port:5432}/test?currentSchema=${datasource.schema:public}
      url: jdbc:postgresql://host.docker.internal:${datasource.port:5432}/test?currentSchema=${datasource.schema:public}
      max-size: 12
      min-size: 2
    write-channel:
      db-kind: postgresql
      username: test_write
      password: test
      jdbc:
        url: jdbc:postgresql://localhost:${datasource.port:5432}/test?currentSchema=${datasource.schema:public}
        max-size: 8
        min-size: 2

app:
  migration:
    db-kind: postgresql
    username: test_write # test_read luego, por ahora test_write
    password: test
    group: pgsql
    location: db/migration/pgsql/changelog.txt
    jdbc:
      # url: jdbc:postgresql://localhost:${datasource.port:5432}/test?currentSchema=${datasource.schema:public}
      url: jdbc:postgresql://host.docker.internal:${datasource.port:5432}/test?currentSchema=${datasource.schema:public}
  