# Database
datasource:
  host: localhost
  port: 5432
  user: test_write
  pass: test
  path: test
  schema: public

# Security
security:
  jwt:
    public:
      key: http://localhost:8080/realms/Test/protocol/openid-connect/certss