# Observability
quarkus:
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"  
  otel:
    traces:
      enabled: true
    logs:
      enabled: true
    exporter:
      otlp:
        traces:
          protocol: ${telemetry.protocol:grpc}
          endpoint: http://${telemetry.host:localhost}:${telemetry.port:4317}        
        logs:
          protocol: ${telemetry.protocol:grpc}
          endpoint: http://${telemetry.host:localhost}:${telemetry.port:4317}

