package org.acme.features.market.place.domain.gateway;

import java.util.Optional;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Slide;
import org.acme.features.market.place.domain.model.Place;
import org.acme.features.market.place.domain.model.PlaceRef;

public interface PlaceReadRepositoryGateway {

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param reference a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Place> enrich(PlaceRef reference);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param uid
   * @param filter a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Boolean> exists(String uid, Optional<PlaceFilter> filter);

  /**
   * The slide with some values
   *
   * @autogenerated ListTraitGenerator
   * @param filter a filter to retrieve only matching values
   * @param cursor a cursor to order and skip
   * @return The slide with some values
   */
  CompletionStage<Slide<Place>> list(PlaceFilter filter, PlaceCursor cursor);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param uid
   * @param filter a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Optional<Place>> retrieve(String uid, Optional<PlaceFilter> filter);
}
