package org.acme.features.market.place.domain.gateway;

import java.util.Optional;
import java.util.concurrent.CompletionStage;

import org.acme.common.store.BinaryContent;
import org.acme.features.market.place.domain.model.Place;

public interface PlacePhotoUploadGateway {

  /**
   * @autogenerated UploadTraitGenerator
   * @param key
   * @param orignal
   * @return
   */
  CompletionStage<String> commitPhoto(Place key, Optional<Place> orignal);

  /**
   * @autogenerated UploadTraitGenerator
   * @param key
   * @return
   */
  CompletionStage<Boolean> deletePhoto(Place key);

  /**
   * @autogenerated UploadTraitGenerator
   * @param entity
   * @return
   */
  CompletionStage<Optional<BinaryContent>> readPhoto(Place entity);

  /**
   * @autogenerated UploadTraitGenerator
   * @param key
   * @return
   */
  CompletionStage<Optional<BinaryContent>> readTemporalPhoto(String key);

  /**
   * @autogenerated UploadTraitGenerator
   * @param content
   * @return
   */
  CompletionStage<String> storeTemporalPhoto(BinaryContent content);
}
