package org.acme.features.market.area.application.usecase.list;

import org.acme.common.action.Interaction;
import org.acme.features.market.area.domain.gateway.AreaCursor;
import org.acme.features.market.area.domain.gateway.AreaFilter;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class AreaListQuery extends Interaction {

  /**
   * The cursor to retrieve a sub set of results
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final AreaCursor cursor;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final AreaFilter filter;
}
