package org.acme.features.market.medal.application.usecase.list;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotAllowedException;
import org.acme.features.market.medal.application.MedalDto;
import org.acme.features.market.medal.application.service.MedalsVisibilityService;
import org.acme.features.market.medal.domain.gateway.MedalCached;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class ListMedalUsecase {

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated ListUsecaseGenerator
   */
  private final Event<MedalListAllow> listAllow;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final MedalsVisibilityService visibility;

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @return
   */
  public MedalListAllow allow(final Interaction query) {
    MedalListAllow base = MedalListAllow.build(query, true, "Allowed by default");
    listAllow.fire(base);
    return base;
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public CompletionStage<MedalListResult> list(final MedalListQuery query) {
    CompletionStage<MedalCached> future = allow(query).getDetail().thenCompose(detail -> {
      if (!detail.isAllowed()) {
        throw new NotAllowedException(detail.getDescription());
      }
      return visibility.listCachedVisibles(query, query.getFilter(), query.getCursor());
    });
    return future.thenCompose(values -> mapList(query, values));
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @param medals
   * @return The slide with some values
   */
  private CompletionStage<MedalListResult> mapList(final MedalListQuery query,
      final MedalCached medals) {
    List<CompletableFuture<MedalDto>> futures =
        medals.getValue().stream().map(medal -> visibility.copyWithHidden(query, medal))
            .map(CompletionStage::toCompletableFuture).toList();
    return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]))
        .thenApply(voidResult -> MedalListResult.builder().query(query)
            .medals(futures.stream().map(CompletableFuture::join).toList()).since(medals.getSince())
            .build());
  }
}
