/* @autogenerated */
package org.acme.common.batch;

import lombok.Builder;
import lombok.Getter;

@Getter
@Builder
public class ExecutorPlan<T> {
  private String name;
  private Executor<T> executor;
  private T params;
}
