package org.acme.features.market.area.domain.gateway;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.function.Function;

import org.acme.common.action.Slide;
import org.acme.features.market.area.domain.model.Area;
import org.acme.features.market.area.domain.model.AreaRef;

public interface AreaWriteRepositoryGateway {

  /**
   * Retrieve one single value
   *
   * @autogenerated CreateTraitGenerator
   * @param entity a filter to retrieve only matching values
   * @param verifier a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Optional<Area>> create(Area entity,
      Function<Area, CompletionStage<Boolean>> verifier);

  /**
   * Retrieve one single value
   *
   * @autogenerated CreateTraitGenerator
   * @param entity a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Optional<Area>> create(Area entity);

  /**
   * Retrieve one single value
   *
   * @autogenerated DeleteTraitGenerator
   * @param entity a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Area> delete(Area entity);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param reference a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Area> enrich(AreaRef reference);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param uid
   * @param filter a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Boolean> exists(String uid, Optional<AreaFilter> filter);

  /**
   * The slide with some values
   *
   * @autogenerated ListTraitGenerator
   * @param filter a filter to retrieve only matching values
   * @param cursor a cursor to order and skip
   * @return The slide with some values
   */
  Slide<Area> list(AreaFilter filter, AreaCursor cursor);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param uid
   * @param filter a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Optional<Area>> retrieve(String uid, Optional<AreaFilter> filter);

  /**
   * Retrieve one single value
   *
   * @autogenerated UpdateTraitGenerator
   * @param reference a filter to retrieve only matching values
   * @param entity a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Area> update(AreaRef reference, Area entity);
}
