package org.acme.features.market.verify.application.usecase.list;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotAllowedException;
import org.acme.common.security.Allow;
import org.acme.features.market.verify.application.VerifyDto;
import org.acme.features.market.verify.application.service.VerifysVisibilityService;
import org.acme.features.market.verify.application.usecase.list.event.VerifyListAllowPipelineStageEvent;
import org.acme.features.market.verify.domain.gateway.VerifyCached;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.StatusCode;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Scope;
import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class ListVerifyUsecase {

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated ListUsecaseGenerator
   */
  private final Event<VerifyListAllowPipelineStageEvent> listAllow;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final VerifysVisibilityService visibility;

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @return
   */
  public CompletionStage<Allow> allow(final Interaction query) {
    Span startSpan = tracer.spanBuilder("verify-list-allow").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      VerifyListAllowPipelineStageEvent base =
          VerifyListAllowPipelineStageEvent.build(query, true, "Allowed by default");
      listAllow.fire(base);
      return base.getDetail().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setAttribute("allowed", val.isAllowed());
          startSpan.setAttribute("reason", val.getDescription());
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public CompletionStage<VerifyListResult> list(final VerifyListQuery query) {
    Span startSpan = tracer.spanBuilder("verify-list").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      CompletionStage<VerifyCached> future = allow(query).thenCompose(detail -> {
        if (!detail.isAllowed()) {
          throw new NotAllowedException(detail.getDescription());
        }
        return visibility.listCachedVisibles(query, query.getFilter(), query.getCursor());
      });
      return future.thenCompose(values -> mapList(query, values)).whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @param verifys
   * @return The slide with some values
   */
  private CompletionStage<VerifyListResult> mapList(final VerifyListQuery query,
      final VerifyCached verifys) {
    Span startSpan = tracer.spanBuilder("verify-map-list-response").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      List<CompletableFuture<VerifyDto>> futures =
          verifys.getValue().stream().map(verify -> visibility.copyWithHidden(query, verify))
              .map(CompletionStage::toCompletableFuture).toList();
      return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]))
          .thenApply(voidResult -> VerifyListResult.builder().query(query)
              .verifys(futures.stream().map(CompletableFuture::join).toList())
              .since(verifys.getSince()).build())
          .whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }
}
