package org.acme.features.market.verify.application.usecase.list;

import org.acme.common.action.Interaction;
import org.acme.features.market.verify.domain.gateway.VerifyCursor;
import org.acme.features.market.verify.domain.gateway.VerifyFilter;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class VerifyListQuery extends Interaction {

  /**
   * The cursor to retrieve a sub set of results
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final VerifyCursor cursor;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final VerifyFilter filter;
}
