package org.acme.features.market.place.infrastructure.driven;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.features.market.place.domain.gateway.PlaceCacheGateway;
import org.acme.features.market.place.domain.gateway.PlaceCached;
import org.acme.features.market.place.domain.gateway.PlaceCursor;
import org.acme.features.market.place.domain.gateway.PlaceFilter;
import org.acme.features.market.place.domain.model.Place;

import io.quarkus.cache.Cache;
import io.quarkus.cache.CacheName;
import jakarta.enterprise.context.RequestScoped;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class PlaceCacheGatewayAdapter implements PlaceCacheGateway {

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   */
  @CacheName("place")
  final Cache cache;

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param place
   * @return
   */
  public CompletionStage<Void> remove(final Place place) {
    return invalidate();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public CompletionStage<Optional<PlaceCached>> retrieve(final PlaceFilter filter,
      final PlaceCursor cursor) {
    String key = key(filter, cursor);
    return cache.<String, PlaceCached>get(key, k -> null).subscribeAsCompletionStage()
        .thenCompose(cached -> cached == null ? notInCache(key)
            : CompletableFuture.completedStage(Optional.of(cached)));
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param filter
   * @param cursor
   * @param places
   * @return
   */
  public CompletionStage<Void> store(final PlaceFilter filter, final PlaceCursor cursor,
      final List<Place> places) {
    String key = key(filter, cursor);
    return cache
        .<String, PlaceCached>get(key,
            k -> PlaceCached.builder().since(OffsetDateTime.now()).value(places).build())
        .subscribeAsCompletionStage().<Void>thenApply(chitem -> null);
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param place
   * @return
   */
  public CompletionStage<Void> update(final Place place) {
    return invalidate();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @return
   */
  private CompletableFuture<Void> invalidate() {
    return cache.invalidateAll().subscribeAsCompletionStage();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private String key(final PlaceFilter filter, final PlaceCursor cursor) {
    return filter.toString() + "-" + cursor.toString();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param key
   * @return
   */
  private CompletableFuture<Optional<PlaceCached>> notInCache(final String key) {
    return cache.invalidateIf(cachekey -> cachekey.equals(key)).subscribeAsCompletionStage()
        .thenApply(_inv -> Optional.empty());
  }
}
