package org.acme.features.market.medal.domain.gateway;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.function.Function;

import org.acme.common.action.Slide;
import org.acme.features.market.medal.domain.model.Medal;
import org.acme.features.market.medal.domain.model.MedalRef;

public interface MedalWriteRepositoryGateway {

  /**
   * Retrieve one single value
   *
   * @autogenerated CreateTraitGenerator
   * @param entity a filter to retrieve only matching values
   * @param verifier a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Optional<Medal>> create(Medal entity,
      Function<Medal, CompletionStage<Boolean>> verifier);

  /**
   * Retrieve one single value
   *
   * @autogenerated CreateTraitGenerator
   * @param entity a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Optional<Medal>> create(Medal entity);

  /**
   * Retrieve one single value
   *
   * @autogenerated DeleteTraitGenerator
   * @param entity a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Medal> delete(Medal entity);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param reference a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Medal> enrich(MedalRef reference);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param uid
   * @param filter a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Boolean> exists(String uid, Optional<MedalFilter> filter);

  /**
   * The slide with some values
   *
   * @autogenerated ListTraitGenerator
   * @param filter a filter to retrieve only matching values
   * @param cursor a cursor to order and skip
   * @return The slide with some values
   */
  CompletionStage<Slide<Medal>> list(MedalFilter filter, MedalCursor cursor);

  /**
   * Retrieve one single value
   *
   * @autogenerated RetrieveTraitGenerator
   * @param uid
   * @param filter a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Optional<Medal>> retrieve(String uid, Optional<MedalFilter> filter);

  /**
   * Retrieve one single value
   *
   * @autogenerated UpdateTraitGenerator
   * @param reference a filter to retrieve only matching values
   * @param entity a filter to retrieve only matching values
   * @return Retrieve one single value
   */
  CompletionStage<Medal> update(MedalRef reference, Medal entity);
}
