package org.acme.features.market.fruit.application.service;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.features.market.fruit.application.FruitDto;
import org.acme.features.market.fruit.application.service.event.FruitFixedFields;
import org.acme.features.market.fruit.application.service.event.FruitHiddenFields;
import org.acme.features.market.fruit.application.service.event.FruitVisibilityQuery;
import org.acme.features.market.fruit.application.service.event.FruitVisibleContent;
import org.acme.features.market.fruit.domain.Fruits;
import org.acme.features.market.fruit.domain.gateway.FruitCacheGateway;
import org.acme.features.market.fruit.domain.gateway.FruitCached;
import org.acme.features.market.fruit.domain.gateway.FruitCursor;
import org.acme.features.market.fruit.domain.gateway.FruitFilter;
import org.acme.features.market.fruit.domain.gateway.FruitReadRepositoryGateway;
import org.acme.features.market.fruit.domain.model.Fruit;
import org.acme.features.market.fruit.domain.model.FruitRef;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class FruitsVisibilityService {

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Fruits aggregate;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final FruitCacheGateway cache;

  /**
   * Event source for maniputale the fix over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitFixedFields> fireFix;

  /**
   * Event source for maniputale the hide over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitHiddenFields> fireHide;

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitVisibilityQuery> fireVisibleFilter;

  /**
   * Event source for maniputale the visible list
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitVisibleContent> fireVisibleList;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final FruitsFormulaService formula;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final FruitReadRepositoryGateway fruitReadRepositoryGateway;

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<Boolean> checkVisibility(Interaction prev, String uid) {
    return retrieveVisible(prev, uid).thenApply(Optional::isPresent);
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param original The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<FruitDto> copyWithFixed(Interaction prev, Fruit original,
      FruitDto source) {
    return fieldsToFix(prev, original).getFixed().thenApply(fixeds -> {
      fixeds.forEach(field -> source.fixField(field, original));
      return source;
    }).thenCompose(fixed -> formula.copyWithFormulas(prev, original, fixed));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<FruitDto> copyWithFixed(Interaction prev, FruitDto source) {
    return fieldsToFix(prev).getFixed().thenApply(fixeds -> {
      fixeds.forEach(field -> source.fixField(field));
      return source;
    }).thenCompose(fixed -> formula.copyWithFormulas(prev, fixed));
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruit
   * @return The input dto with hidden values
   */
  public CompletionStage<FruitDto> copyWithHidden(Interaction prev, Fruit fruit) {
    return fieldsToHide(prev, fruit).getHidden().thenApply(hidden -> {
      FruitDto target = FruitDto.from(fruit);
      hidden.forEach(target::hideField);
      return target;
    });
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsFixFields
   */
  public FruitFixedFields fieldsToFix(Interaction prev) {
    CompletionStage<Set<String>> fields = fieldsToHide(prev).getHidden().thenApply(hidden -> {
      Set<String> set = new HashSet<>(aggregate.calcultadFields());
      set.addAll(hidden);
      return set;
    });
    FruitFixedFields value = FruitFixedFields.builder().fixed(fields).build(prev);
    fireFix.fire(value);
    return value;
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruit
   * @return initialsFixFields
   */
  public FruitFixedFields fieldsToFix(Interaction prev, FruitRef fruit) {
    CompletionStage<Set<String>> fields = fieldsToFix(prev).getFixed()
        .thenCombine(fieldsToHide(prev, fruit).getHidden(), (set1, set2) -> {
          Set<String> set = new HashSet<>(set1);
          set.addAll(set2);
          return set;
        });
    FruitFixedFields value = FruitFixedFields.builder().fixed(fields).fruit(fruit).build(prev);
    fireFix.fire(value);
    return value;
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsHideFields
   */
  public FruitHiddenFields fieldsToHide(Interaction prev) {
    CompletionStage<Set<String>> fields = CompletableFuture.completedFuture(Set.of());
    FruitHiddenFields value = FruitHiddenFields.builder().hidden(fields).build(prev);
    fireHide.fire(value);
    return value;
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruit
   * @return initialsHideFields
   */
  public FruitHiddenFields fieldsToHide(Interaction prev, FruitRef fruit) {
    CompletionStage<Set<String>> fields = fieldsToHide(prev).getHidden();
    FruitHiddenFields value = FruitHiddenFields.builder().hidden(fields).fruit(fruit).build(prev);
    fireHide.fire(value);
    return value;
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<FruitCached> listCachedVisibles(Interaction prev, FruitFilter filter,
      FruitCursor cursor) {
    return applyPreVisibilityFilter(prev, filter)
        .thenCompose(visfilter -> cache.retrieve(visfilter, cursor).thenCompose(cached -> {
          if (cached.isPresent()) {
            return CompletableFuture.completedStage(cached.get());
          } else {
            return queryItems(prev, filter, cursor).thenApply(values -> {
              cache.store(filter, cursor, values);
              return FruitCached.builder().value(values).since(OffsetDateTime.now()).build();
            });
          }
        }));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<List<Fruit>> listVisibles(Interaction prev, FruitFilter filter,
      FruitCursor cursor) {
    return applyPreVisibilityFilter(prev, filter)
        .thenCompose(visfilter -> queryItems(prev, visfilter, cursor));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<FruitCached> retrieveCachedVisible(Interaction prev, String uid) {
    return applyPreVisibilityFilter(prev, FruitFilter.builder().uid(uid).build())
        .thenCompose(filter -> {
          filter.setUid(uid);
          FruitCursor cursor = FruitCursor.builder().limit(1).build();
          return cache.retrieve(filter, cursor).thenCompose(cached -> {
            if (cached.isPresent()) {
              return CompletableFuture.completedStage(cached.get());
            } else {
              return queryItem(prev, uid, filter).thenApply(value -> {
                List<Fruit> values = value.map(List::of).orElseGet(List::of);
                cache.store(filter, cursor, values);
                return FruitCached.builder().value(values).since(OffsetDateTime.now()).build();
              });
            }
          });
        });
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<Optional<Fruit>> retrieveVisible(Interaction prev, String uid) {
    return applyPreVisibilityFilter(prev, FruitFilter.builder().uid(uid).build())
        .thenCompose(filter -> queryItem(prev, uid, filter));
  }

  /**
   * The self filter modified with the prepared values.
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @return The self filter modified with the prepared values.
   */
  private CompletionStage<FruitFilter> applyPreVisibilityFilter(Interaction prev,
      FruitFilter filter) {
    FruitVisibilityQuery visible = FruitVisibilityQuery.builder()
        .filter(CompletableFuture.completedFuture(filter)).build(prev);
    fireVisibleFilter.fire(visible);
    return visible.getFilter();
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruitRefs The source interaction
   * @return The input dto with hidden values
   */
  private CompletionStage<List<Fruit>> evaluatePostVisibility(Interaction prev,
      List<Fruit> fruitRefs) {
    FruitVisibleContent list = FruitVisibleContent.builder()
        .visibles(CompletableFuture.completedFuture(new ArrayList<>(fruitRefs))).build(prev);
    fireVisibleList.fire(list);
    return list.getVisibles();
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruitRef The source interaction
   * @return The input dto with hidden values
   */
  private CompletionStage<Optional<Fruit>> evaluatePostVisibility(Interaction prev,
      Fruit fruitRef) {
    return evaluatePostVisibility(prev, List.of(fruitRef))
        .thenApply(list -> list.isEmpty() ? Optional.empty() : Optional.of(list.get(0)));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private CompletionStage<Optional<Fruit>> queryItem(Interaction prev, String uid,
      FruitFilter filter) {
    return fruitReadRepositoryGateway.retrieve(uid, Optional.of(filter))
        .thenCompose(stored -> stored.map(retrieved -> evaluatePostVisibility(prev, retrieved))
            .orElseGet(() -> CompletableFuture.completedStage(Optional.empty())));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private CompletionStage<List<Fruit>> queryItems(Interaction prev, FruitFilter filter,
      FruitCursor cursor) {
    return fruitReadRepositoryGateway.list(filter, cursor)
        .filterAndFillAgain(values -> evaluatePostVisibility(prev, values));
  }
}
