package org.acme.features.market.merchant.application.interaction.command;

import org.acme.common.action.Interaction;
import org.acme.features.market.merchant.application.interaction.MerchantDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class MerchantCreateCommand extends Interaction {

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final MerchantDto dto;
}
