package org.acme.features.market.fruit.application;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

import org.acme.features.market.fruit.domain.model.Fruit;
import org.acme.features.market.fruit.domain.model.Fruit.FruitBuilder;
import org.acme.features.market.fruit.domain.model.valueobject.FruitNameVO;
import org.acme.features.market.fruit.domain.model.valueobject.FruitUidVO;
import org.acme.features.market.fruit.domain.model.valueobject.FruitVersionVO;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class FruitDto {

  /**
   * A dto with the entity data
   *
   * @autogenerated EntityGenerator
   * @param fruit The entity with the values
   * @return A dto with the entity data
   */
  public static FruitDto from(final Fruit fruit) {
    return FruitDto.builder().uid(fruit.getUid()).name(fruit.getName()).version(fruit.getVersion())
        .build();
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  private static Map<String, BiConsumer<FruitDto, Fruit>> buildToFix() {
    Map<String, BiConsumer<FruitDto, Fruit>> map = new HashMap<>();
    map.put("uid", (target, source) -> target.uid = source == null ? null : source.getUid());
    map.put("name", (target, source) -> target.name = source == null ? null : source.getName());
    map.put("version",
        (target, source) -> target.version = source == null ? null : source.getVersion());
    return map;
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  private static Map<String, Consumer<FruitDto>> buildToHide() {
    Map<String, Consumer<FruitDto>> map = new HashMap<>();
    map.put("uid", dto -> dto.uid = null);
    map.put("name", dto -> dto.name = null);
    map.put("version", dto -> dto.version = null);
    return map;
  }

  /**
   * @autogenerated EntityGenerator
   */
  private FruitNameVO name;

  /**
   * @autogenerated EntityGenerator
   */
  private FruitUidVO uid;

  /**
   * @autogenerated EntityGenerator
   */
  private FruitVersionVO version;

  /**
   * Hide a field value for the dto (setting as null)
   *
   * @autogenerated EntityGenerator
   * @param field The field to hide
   * @param fruit The field to hide
   */
  public void fixField(final String field, final Fruit fruit) {
    Map<String, BiConsumer<FruitDto, Fruit>> toFix = buildToFix();
    if (toFix.containsKey(field)) {
      toFix.get(field).accept(this, fruit);
    }
  }

  /**
   * Hide a field value for the dto (setting as null)
   *
   * @autogenerated EntityGenerator
   * @param field The field to hide
   */
  public void fixField(final String field) {
    fixField(field, null);
  }

  /**
   * Hide a field value for the dto (setting as null)
   *
   * @autogenerated EntityGenerator
   * @param field The field to hide
   */
  public void hideField(final String field) {
    Map<String, Consumer<FruitDto>> toHide = buildToHide();
    if (toHide.containsKey(field)) {
      toHide.get(field).accept(this);
    }
  }

  /**
   * The entity param with the new values
   *
   * @autogenerated EntityGenerator
   * @param original
   * @return The entity param with the new values
   */
  public FruitBuilder toEntityBuilder(final Optional<Fruit> original) {
    FruitBuilder builder = Fruit.builder();
    builder = setUidOrDefault(builder, original);
    builder = setNameOrDefault(builder, original);
    builder = setVersionOrDefault(builder, original);
    return builder;
  }

  /**
   * @autogenerated EntityGenerator
   * @param builder
   * @param original
   * @return
   */
  private Fruit.FruitBuilder setNameOrDefault(final FruitBuilder builder,
      final Optional<Fruit> original) {
    FruitNameVO value = null == name ? original.map(Fruit::getName).orElse(null) : name;
    return null == value ? builder : builder.name(value);
  }

  /**
   * @autogenerated EntityGenerator
   * @param builder
   * @param original
   * @return
   */
  private Fruit.FruitBuilder setUidOrDefault(final FruitBuilder builder,
      final Optional<Fruit> original) {
    FruitUidVO value = null == uid ? original.map(Fruit::getUid).orElse(null) : uid;
    return null == value ? builder : builder.uid(value);
  }

  /**
   * @autogenerated EntityGenerator
   * @param builder
   * @param original
   * @return
   */
  private Fruit.FruitBuilder setVersionOrDefault(final FruitBuilder builder,
      final Optional<Fruit> original) {
    FruitVersionVO value = null == version ? original.map(Fruit::getVersion).orElse(null) : version;
    return null == value ? builder : builder.version(value);
  }
}
