package org.acme.features.market.merchant.application.usecase.retrieve;

import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotAllowedException;
import org.acme.features.market.merchant.application.service.MerchantsVisibilityService;
import org.acme.features.market.merchant.domain.gateway.MerchantCached;
import org.acme.features.market.merchant.domain.model.MerchantRef;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class RetrieveMerchantUsecase {

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated ListUsecaseGenerator
   */
  private final Event<MerchantRetrieveAllow> retrieveAllow;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final MerchantsVisibilityService visibility;

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public MerchantRetrieveAllow allow(final Interaction query, final MerchantRef reference) {
    MerchantRetrieveAllow base =
        MerchantRetrieveAllow.build(query, Optional.of(reference), true, "Allowed by default");
    retrieveAllow.fire(base);
    return base;
  }

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @return
   */
  public MerchantRetrieveAllow allow(final Interaction query) {
    MerchantRetrieveAllow base =
        MerchantRetrieveAllow.build(query, Optional.empty(), true, "Allowed by default");
    retrieveAllow.fire(base);
    return base;
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public CompletionStage<MerchantRetrieveResult> retrieve(final MerchantRetrieveQuery query) {
    CompletionStage<MerchantCached> result =
        allow(query, query.getReference()).getDetail().thenCompose(detail -> {
          if (!detail.isAllowed()) {
            throw new NotAllowedException(detail.getDescription());
          }
          return visibility.retrieveCachedVisible(query, query.getReference().getUidValue());
        });
    return result.thenCompose(op -> this.mapEntity(query, op));
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @param opmerchant
   * @return The slide with some values
   */
  private CompletionStage<MerchantRetrieveResult> mapEntity(final MerchantRetrieveQuery query,
      final MerchantCached opmerchant) {
    return opmerchant.first()
        .map(merchant -> visibility.copyWithHidden(query, merchant)
            .thenApply(merchantWithHidden -> MerchantRetrieveResult.builder().interaction(query)
                .merchant(Optional.of(merchantWithHidden)).since(opmerchant.getSince()).build()))
        .orElseGet(() -> CompletableFuture.completedFuture(MerchantRetrieveResult.builder()
            .interaction(query).merchant(Optional.empty()).since(OffsetDateTime.now()).build()));
  }
}
