package org.acme.features.market.place.application.service.proposal;

import java.util.Optional;

import org.acme.common.security.PropertiesProposal;
import org.acme.features.market.place.domain.model.PlaceRef;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class PlaceHiddenFieldsProposal extends PropertiesProposal {

  /**
   * @autogenerated HiddenFieldsProposalGenerator
   */
  private final PlaceRef place;

  /**
   * @autogenerated HiddenFieldsProposalGenerator
   * @return
   */
  public Optional<PlaceRef> getPlace() {
    return Optional.ofNullable(place);
  }

  /**
   * @autogenerated HiddenFieldsProposalGenerator
   * @return
   */
  public String resourceName() {
    return "place";
  }

  /**
   * @autogenerated HiddenFieldsProposalGenerator
   * @return
   */
  public String viewName() {
    return "view";
  }
}
