package org.acme.features.market.area.domain.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AreaReferenceUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test a entity reference contruction")
  void test_area_reference_builder() {
    AreaReference ref = AreaReference.of("one");
    Assertions.assertEquals("one", ref.getUid().getValue());
  }
}
