package org.acme.features.market.fruit.application.service.event;

import java.util.concurrent.CompletionStage;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.UnaryOperator;

import org.acme.common.action.Interaction;
import org.acme.features.market.fruit.domain.gateway.FruitFilter;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class FruitVisibilityQuery extends Interaction {

  /**
   * @autogenerated VisibleContentGenerator
   */
  @NonNull
  private CompletionStage<FruitFilter> filter;

  /**
   * @autogenerated VisibleContentGenerator
   * @param mapper
   */
  public void flatMap(Function<FruitFilter, CompletionStage<FruitFilter>> mapper) {
    filter = filter.thenCompose(mapper);
  }

  /**
   * @autogenerated VisibleContentGenerator
   * @param mapper
   */
  public void map(UnaryOperator<FruitFilter> mapper) {
    filter = filter.thenApply(mapper);
  }

  /**
   * @autogenerated VisibleContentGenerator
   * @param mapper
   */
  public void tap(Consumer<FruitFilter> mapper) {
    filter = filter.thenApply(filter -> {
      mapper.accept(filter);
      return filter;
    });
  }
}
