package org.acme.features.market.fruit.application.service.event;

import java.util.Optional;

import org.acme.common.security.PropertiesPipelineStageEvent;
import org.acme.features.market.fruit.domain.model.FruitRef;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
@SuperBuilder(toBuilder = true)
public class FruitFixedFieldsPipelineStageEvent extends PropertiesPipelineStageEvent {

  /**
   * @autogenerated FixedFieldsPipelineStageEventGenerator
   */
  private final FruitRef fruit;

  /**
   * @autogenerated FixedFieldsPipelineStageEventGenerator
   * @return
   */
  public Optional<FruitRef> getFruit() {
    return Optional.ofNullable(fruit);
  }

  /**
   * @autogenerated FixedFieldsPipelineStageEventGenerator
   * @return
   */
  public String resourceName() {
    return "fruit";
  }

  /**
   * @autogenerated FixedFieldsPipelineStageEventGenerator
   * @return
   */
  public String viewName() {
    return "update";
  }
}
