package org.acme.features.market.color.application.usecase.list;

import java.time.OffsetDateTime;
import java.util.List;

import org.acme.features.market.color.application.ColorDto;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class ColorListResult {

  /**
   * The result content list
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final List<ColorDto> colors;

  /**
   * The result content list
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final ColorListQuery query;

  /**
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final OffsetDateTime since;
}
