package org.acme.features.market.fruit.application.usecase.update;

import org.acme.common.action.Interaction;
import org.acme.features.market.fruit.application.FruitDto;
import org.acme.features.market.fruit.application.service.proposal.FruitModifyProposal;
import org.acme.features.market.fruit.domain.model.Fruit;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class FruitUpdateProposal extends FruitModifyProposal {

  /**
   * @autogenerated UpdateProposalGenerator
   * @param emitter
   * @param interaction
   * @param dto
   * @param entity
   * @return
   */
  public static FruitDto resolveWith(final Event<FruitUpdateProposal> emitter,
      final Interaction interaction, final FruitDto dto, final Fruit entity) {
    return resolveWith(emitter,
        FruitUpdateProposal.builder().interaction(interaction).dto(dto).entity(entity).build());
  }
}
