package org.acme.features.market.fruit.domain.model.rule;

import java.util.Iterator;

import org.acme.features.market.fruit.domain.model.Fruit;

public interface FruitDeleteRulePipeline {

  /**
   * @autogenerated AggregateGenerator
   * @param rules
   * @param fruit
   * @return
   */
  public static Fruit fire(Iterator<FruitDeleteRulePipeline> rules, Fruit fruit) {
    Fruit result = fruit;
    while (rules.hasNext()) {
      result = rules.next().deleting(result);
    }
    return result;
  }

  /**
   * @autogenerated AggregateGenerator
   * @param fruit
   * @return
   */
  Fruit deleting(Fruit fruit);
}
