package org.acme.features.market.fruit.application.usecase.service;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

import org.acme.common.action.Interaction;
import org.acme.features.market.fruit.application.interaction.FruitDto;
import org.acme.features.market.fruit.application.interaction.visibility.FruitFixedFields;
import org.acme.features.market.fruit.application.interaction.visibility.FruitHiddenFields;
import org.acme.features.market.fruit.application.interaction.visibility.FruitListableContent;
import org.acme.features.market.fruit.application.interaction.visibility.FruitVisibleContent;
import org.acme.features.market.fruit.application.interaction.visibility.FruitVisibleFilter;
import org.acme.features.market.fruit.domain.Fruits;
import org.acme.features.market.fruit.domain.gateway.FruitFilter;
import org.acme.features.market.fruit.domain.model.Fruit;
import org.acme.features.market.fruit.domain.model.FruitRef;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class FruitsVisibilityService {

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Fruits aggregate;

  /**
   * Event source for maniputale the fix over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitFixedFields> fireFix;

  /**
   * Event source for maniputale the hide over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitHiddenFields> fireHide;

  /**
   * Event source for maniputale the visible list
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitListableContent> fireListableList;

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitVisibleFilter> fireVisibleFilter;

  /**
   * Event source for maniputale the visible list
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<FruitVisibleContent> fireVisibleList;

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param original The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public CompletableFuture<FruitDto> copyWithFixed(Interaction prev, Fruit original,
      FruitDto source) {
    return fieldsToFix(prev, original).getFixed().thenApply(fixeds -> {
      fixeds.forEach(field -> source.fix(field, original));
      return source;
    });
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public CompletableFuture<FruitDto> copyWithFixed(Interaction prev, FruitDto source) {
    return fieldsToFix(prev).getFixed().thenApply(fixeds -> {
      fixeds.forEach(field -> source.fix(field));
      return source;
    });
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsFixFields
   */
  public FruitFixedFields fieldsToFix(Interaction prev) {
    CompletableFuture<Set<String>> fields = fieldsToHide(prev).getHidden().thenApply(hidden -> {
      Set<String> set = new HashSet<>(aggregate.calcultadFields());
      set.addAll(hidden);
      return set;
    });
    FruitFixedFields value = FruitFixedFields.builder().fixed(fields).build(prev);
    fireFix.fire(value);
    return value;
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruit
   * @return initialsFixFields
   */
  public FruitFixedFields fieldsToFix(Interaction prev, FruitRef fruit) {
    CompletableFuture<Set<String>> fields = fieldsToFix(prev).getFixed()
        .thenCombine(fieldsToHide(prev, fruit).getHidden(), (set1, set2) -> {
          Set<String> set = new HashSet<>(set1);
          set.addAll(set2);
          return set;
        });
    FruitFixedFields value = FruitFixedFields.builder().fixed(fields).fruit(fruit).build(prev);
    fireFix.fire(value);
    return value;
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsHideFields
   */
  public FruitHiddenFields fieldsToHide(Interaction prev) {
    CompletableFuture<Set<String>> fields = CompletableFuture.completedFuture(Set.of());
    FruitHiddenFields value = FruitHiddenFields.builder().hidden(fields).build(prev);
    fireHide.fire(value);
    return value;
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruit
   * @return initialsHideFields
   */
  public FruitHiddenFields fieldsToHide(Interaction prev, FruitRef fruit) {
    CompletableFuture<Set<String>> fields = fieldsToHide(prev).getHidden();
    FruitHiddenFields value = FruitHiddenFields.builder().hidden(fields).fruit(fruit).build(prev);
    fireHide.fire(value);
    return value;
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruit
   * @return The input dto with hidden values
   */
  public CompletableFuture<FruitDto> hide(Interaction prev, Fruit fruit) {
    return fieldsToHide(prev, fruit).getHidden().thenApply(hidden -> {
      FruitDto target = FruitDto.from(fruit);
      hidden.forEach(target::hide);
      return target;
    });
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruitRefs The source interaction
   * @return The input dto with hidden values
   */
  public CompletableFuture<List<Fruit>> listableFilter(Interaction prev, List<Fruit> fruitRefs) {
    return visibleFilter(prev, fruitRefs).thenCompose(visibles -> {
      FruitListableContent list = FruitListableContent.builder()
          .listables(CompletableFuture.completedFuture(visibles)).build(prev);
      fireListableList.fire(list);
      return list.getListables();
    });
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruitRefs The source interaction
   * @return The input dto with hidden values
   */
  public CompletableFuture<List<Fruit>> visibleFilter(Interaction prev, List<Fruit> fruitRefs) {
    FruitVisibleContent list = FruitVisibleContent.builder()
        .visibles(CompletableFuture.completedFuture(new ArrayList<>(fruitRefs))).build(prev);
    fireVisibleList.fire(list);
    return list.getVisibles();
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param fruitRef The source interaction
   * @return The input dto with hidden values
   */
  public CompletableFuture<Optional<Fruit>> visibleFilter(Interaction prev, Fruit fruitRef) {
    return visibleFilter(prev, List.of(fruitRef))
        .thenApply(list -> list.isEmpty() ? Optional.empty() : Optional.of(list.get(0)));
  }

  /**
   * The self filter modified with the prepared values.
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @return The self filter modified with the prepared values.
   */
  public CompletableFuture<FruitFilter> visibleFilter(Interaction prev, FruitFilter filter) {
    FruitVisibleFilter visible =
        FruitVisibleFilter.builder().filter(CompletableFuture.completedFuture(filter)).build(prev);
    fireVisibleFilter.fire(visible);
    return visible.getFilter();
  }
}
