package org.acme;

import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.QuarkusApplication;

public class TestApplication implements QuarkusApplication {

  /**
   * @autogenerated quarkusgenerator
   * @param args
   */
  public static void main(String... args) {
    System.setProperty("liquibase.secureParsing", "false");
    Quarkus.run(TestApplication.class, args);
  }

  /**
   * @autogenerated quarkusgenerator
   * @param args
   * @return
   */
  @Override
  public int run(String... args) throws Exception {
    Quarkus.waitForExit();
    return 0;
  }
}
