package org.acme.features.market.area.application.usecase.update;

import org.acme.common.action.Interaction;
import org.acme.features.market.area.application.service.event.AreaEntityEvent;
import org.acme.features.market.area.domain.model.Area;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class AreaUpdateEvent extends AreaEntityEvent {

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @param emitter
   * @param interaction
   * @param entity
   */
  @SuppressWarnings("unchecked")
  public static void notifyWith(final Event<? extends AreaUpdateEvent> emitter,
      final Interaction interaction, final Area entity) {
    ((Event<AreaUpdateEvent>) emitter)
        .fire(AreaUpdateEvent.builder().interaction(interaction).entity(entity).build());
  }

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @return
   */
  @Override
  public String operation() {
    return "update";
  }
}
