package org.acme.features.market.verify.domain.model.valueobject;

import org.acme.common.exception.ConstraintException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class VerifyMedalUidVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property uid of verify medal ")
  void test_verify_medal_uid_v_o_builder() {
    Assertions.assertThrows(ConstraintException.class, () -> VerifyMedalUidVO.tryFrom(null));
    Assertions.assertEquals("one", VerifyMedalUidVO.from("one").getValue());
    Assertions.assertThrows(ConstraintException.class,
        () -> VerifyMedalUidVO.tryFrom(new Object() {}));
  }
}
