package org.acme.features.market.area.application.usecase.delete;

import java.util.List;

import org.acme.common.batch.stepper.ItemDescriptor;
import org.acme.common.batch.stepper.ItemProcessor;
import org.acme.common.batch.stepper.ItemReader;
import org.acme.common.batch.stepper.ItemWriter;
import org.acme.common.batch.stepper.StepContext;
import org.acme.common.batch.stepper.StepCounter;
import org.acme.common.batch.stepper.StepFinalizer;
import org.acme.common.batch.stepper.StepInitializer;
import org.acme.common.exception.ExecutionException;
import org.acme.common.security.Allow;
import org.acme.features.market.area.application.service.AreasVisibilityService;
import org.acme.features.market.area.domain.gateway.AreaCursor;
import org.acme.features.market.area.domain.model.Area;

import io.quarkus.arc.Unremovable;
import jakarta.enterprise.context.RequestScoped;
import lombok.Data;
import lombok.RequiredArgsConstructor;

@Unremovable
@RequestScoped
@RequiredArgsConstructor
class DeleteAreasInBatchExecutor implements
    StepCounter<AreaDeleteAllInBatchCommand, DeleteAreasInBatchExecutor.AreaPaginableBatch>,
    StepFinalizer<AreaDeleteAllInBatchCommand, DeleteAreasInBatchExecutor.AreaPaginableBatch>,
    StepInitializer<AreaDeleteAllInBatchCommand, DeleteAreasInBatchExecutor.AreaPaginableBatch>,
    ItemReader<Area, AreaDeleteAllInBatchCommand, DeleteAreasInBatchExecutor.AreaPaginableBatch>,
    ItemWriter<Area, AreaDeleteAllInBatchCommand, DeleteAreasInBatchExecutor.AreaPaginableBatch>,
    ItemProcessor<Area, Area, AreaDeleteAllInBatchCommand, DeleteAreasInBatchExecutor.AreaPaginableBatch>,
    ItemDescriptor<Area, AreaDeleteAllInBatchCommand, DeleteAreasInBatchExecutor.AreaPaginableBatch> {

  /**
   * @autogenerated EntityGenerator
   */
  @Data
  public static class AreaPaginableBatch {

    /**
     * @autogenerated EntityGenerator
     */
    private String since;
  }

  /**
   * @autogenerated EntityGenerator
   */
  private final int size = 10;

  /**
   * @autogenerated EntityGenerator
   */
  private final DeleteAreaUsecase usecase;

  /**
   * @autogenerated EntityGenerator
   */
  private final AreasVisibilityService visibility;

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public long approximatedItems(
      final StepContext<AreaDeleteAllInBatchCommand, AreaPaginableBatch> context) {
    return visibility.countVisibles(context.getParams(), context.getParams().getFilter());
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void finish(final StepContext<AreaDeleteAllInBatchCommand, AreaPaginableBatch> context) {
    usecase.flush();
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void init(final StepContext<AreaDeleteAllInBatchCommand, AreaPaginableBatch> context) {
    context.setState(new AreaPaginableBatch());
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public String itemDescription(final Area item,
      final StepContext<AreaDeleteAllInBatchCommand, AreaPaginableBatch> context) {
    return item.getUidValue();
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public Area process(final Area item,
      final StepContext<AreaDeleteAllInBatchCommand, AreaPaginableBatch> context) {
    Allow allowed = usecase.allow(context.getParams(), item);
    if (!allowed.isAllowed()) {
      throw new ExecutionException("not-allowed", null);
    }
    return item;
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public List<Area> read(
      final StepContext<AreaDeleteAllInBatchCommand, AreaPaginableBatch> context) {
    List<Area> page = visibility.listVisibles(context.getParams(), context.getParams().getFilter(),
        AreaCursor.builder().limit(size).sinceUid(context.getState().getSince()).build());
    context.getState().setSince(page.isEmpty() ? null : page.get(page.size() - 1).getUidValue());
    return page;
  }

  /**
   * @autogenerated EntityGenerator
   * @param items
   * @param context
   */
  @Override
  public void write(final List<Area> items,
      final StepContext<AreaDeleteAllInBatchCommand, AreaPaginableBatch> context) {
    items.forEach(item -> usecase.delete(context.getParams(), item));
  }
}
