/* @autogenerated */
package org.acme.common.store;

import java.io.InputStream;

import lombok.Builder;
import lombok.Getter;

@Getter
@Builder
public class BinaryContent {
  private final InputStream inputStream;
  private final String contentType;
  private final String name;
  private final Long lastModification;
}
