/* @autogenerated */
package org.acme.common.infrastructure.connector;

import org.acme.common.connector.RemoteConnector;
import org.acme.common.infrastructure.connector.munity.MunityWebConnector;
import io.vertx.mutiny.core.Vertx;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;

@ApplicationScoped
public class ConnectorProducer {

  @Produces
  @ApplicationScoped
  public RemoteConnector connector(Vertx vertx) {
    return new MunityWebConnector(vertx);
  }
}
