package org.acme.features.market.verify.domain.gateway;

public enum VerifyOrder {

  /**
   * @autogenerated OrderGenerator
   */
  NAME_ASC,
  /**
   * @autogenerated OrderGenerator
   */
  NAME_DESC
}
