package org.acme.features.market.place.domain.model.valueobject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class PlacePhotoVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property photo of place ")
  void test_place_photo_v_o_builder() {
    Assertions.assertEquals("goo", PlacePhotoVO.from("goo").getValue().orElse(null));
  }
}
