package org.acme.features.market.verify.application.service.proposal;

import java.util.Optional;
import java.util.function.Consumer;

import org.acme.common.action.Interaction;
import org.acme.features.market.verify.application.VerifyDto;
import org.acme.features.market.verify.domain.model.Verify;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class VerifyCalculatedProposal {

  /**
   * @autogenerated CalculatorBuilderProposalGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated CalculatorBuilderProposalGenerator
   */
  @NonNull
  private VerifyDto dto;

  /**
   * @autogenerated CalculatorBuilderProposalGenerator
   */
  private Verify original;

  /**
   * @autogenerated CalculatorBuilderProposalGenerator
   * @return
   */
  public Optional<Verify> getOriginal() {
    return Optional.ofNullable(original);
  }

  /**
   * @autogenerated CalculatorBuilderProposalGenerator
   * @param mapper
   */
  public void peek(Consumer<VerifyDto> mapper) {
    mapper.accept(dto);
  }
}
