package org.acme.features.market.verify.application.service.proposal;

import org.acme.common.action.Interaction;
import org.acme.features.market.verify.domain.model.VerifyRef;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public abstract class VerifyRemoveProposal {

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @param emitter
   * @param proposal
   * @return
   */
  @SuppressWarnings("unchecked")
  public static VerifyRef resolveWith(final Event<? extends VerifyRemoveProposal> emitter,
      final VerifyRemoveProposal proposal) {
    ((Event<VerifyRemoveProposal>) emitter).fire(proposal);
    return proposal.getReference();
  }

  /**
   * @autogenerated VisibleContentProposalGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated VisibleContentProposalGenerator
   */
  @NonNull
  private VerifyRef reference;
}
