package org.acme.features.market.verify.infrastructure.driven;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.features.market.verify.domain.gateway.VerifyCacheGateway;
import org.acme.features.market.verify.domain.gateway.VerifyCached;
import org.acme.features.market.verify.domain.gateway.VerifyCursor;
import org.acme.features.market.verify.domain.gateway.VerifyFilter;
import org.acme.features.market.verify.domain.model.Verify;

import io.quarkus.cache.Cache;
import io.quarkus.cache.CacheName;
import jakarta.enterprise.context.RequestScoped;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@RequestScoped
@RequiredArgsConstructor
@Slf4j
public class VerifyCacheGatewayAdapter implements VerifyCacheGateway {

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   */
  @CacheName("verify")
  private final Cache cache;

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param verify
   * @return
   */
  public CompletionStage<Void> remove(final Verify verify) {
    log.trace("Invalidating verify cache due to the removal of {}", verify);
    return invalidate();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public CompletionStage<Optional<VerifyCached>> retrieve(final VerifyFilter filter,
      final VerifyCursor cursor) {
    String key = key(filter, cursor);
    log.trace("Lookup at verify cache for the key {}", key);
    return cache.<String, VerifyCached>get(key, k -> null).subscribeAsCompletionStage()
        .thenCompose(cached -> cached == null ? notInCache(key) : existingValue(key, cached));
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param filter
   * @param cursor
   * @param verifys
   * @return
   */
  public CompletionStage<Void> store(final VerifyFilter filter, final VerifyCursor cursor,
      final List<Verify> verifys) {
    String key = key(filter, cursor);
    return cache
        .<String, VerifyCached>get(key,
            k -> VerifyCached.builder().since(OffsetDateTime.now()).value(verifys).build())
        .subscribeAsCompletionStage().<Void>thenApply(chitem -> null);
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param verify
   * @return
   */
  public CompletionStage<Void> update(final Verify verify) {
    log.trace("Invalidating verify cache due to the update of {}", verify);
    return invalidate();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param key
   * @param cached
   * @return
   */
  private CompletionStage<Optional<VerifyCached>> existingValue(final String key,
      final VerifyCached cached) {
    log.trace("There is value for key {} in the cache verify: {}", key, cached);
    return CompletableFuture.completedStage(Optional.of(cached));
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @return
   */
  private CompletableFuture<Void> invalidate() {
    return cache.invalidateAll().subscribeAsCompletionStage();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private String key(final VerifyFilter filter, final VerifyCursor cursor) {
    return filter.toString() + "-" + cursor.toString();
  }

  /**
   * @autogenerated CacheAdaterGatewayGenerator
   * @param key
   * @return
   */
  private CompletableFuture<Optional<VerifyCached>> notInCache(final String key) {
    log.trace("There is no value for key {} on the cache verify", key);
    return cache.invalidateIf(cachekey -> cachekey.equals(key)).subscribeAsCompletionStage()
        .thenApply(_inv -> Optional.empty());
  }
}
