package org.acme.features.market.place.domain.model;

import org.acme.features.market.place.domain.model.valueobject.PlaceUidVO;

public interface PlaceRef {

  /**
   * @autogenerated EntityReferenceGenerator
   * @return
   */
  PlaceUidVO getUid();

  /**
   * @autogenerated EntityReferenceGenerator
   * @return
   */
  String getUidValue();
}
