package org.acme.features.market.color.domain.model.valueobject;

import org.acme.common.exception.ConstraintException;
import org.acme.features.market.merchant.domain.model.MerchantReference;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class ColorMerchantVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property merchant of color ")
  void test_color_merchant_v_o_builder() {
    Assertions.assertFalse(ColorMerchantVO.empty().getValue().isPresent(),
        "A empty vo should have a null value");
    Assertions.assertFalse(ColorMerchantVO.tryFrom(null).getValue().isPresent());
    Assertions.assertEquals(MerchantReference.of("one"),
        ColorMerchantVO.from(MerchantReference.of("one")).getValue().orElse(null));
    Assertions.assertThrows(ConstraintException.class,
        () -> ColorMerchantVO.tryFrom(new Object() {}));
  }
}
