package org.acme.features.market.verify.application.service;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotFoundException;
import org.acme.features.market.medal.application.service.MedalsVisibilityService;
import org.acme.features.market.verify.application.VerifyDto;
import org.acme.features.market.verify.application.service.event.VerifyFixedFieldsPipelineStageEvent;
import org.acme.features.market.verify.application.service.event.VerifyHiddenFieldsPipelineStageEvent;
import org.acme.features.market.verify.application.service.event.VerifyVisibilityQueryPipelineStageEvent;
import org.acme.features.market.verify.application.service.event.VerifyVisibleContentPipelineStageEvent;
import org.acme.features.market.verify.domain.Verifys;
import org.acme.features.market.verify.domain.gateway.VerifyCacheGateway;
import org.acme.features.market.verify.domain.gateway.VerifyCached;
import org.acme.features.market.verify.domain.gateway.VerifyCursor;
import org.acme.features.market.verify.domain.gateway.VerifyFilter;
import org.acme.features.market.verify.domain.gateway.VerifyReadRepositoryGateway;
import org.acme.features.market.verify.domain.model.Verify;
import org.acme.features.market.verify.domain.model.VerifyRef;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.StatusCode;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Scope;
import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class VerifysVisibilityService {

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Verifys aggregate;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final VerifyCacheGateway cache;

  /**
   * Event source for maniputale the fix over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<VerifyFixedFieldsPipelineStageEvent> fireFix;

  /**
   * Event source for maniputale the hide over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<VerifyHiddenFieldsPipelineStageEvent> fireHide;

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<VerifyVisibilityQueryPipelineStageEvent> fireVisibleFilter;

  /**
   * Event source for maniputale the visible list
   *
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<VerifyVisibleContentPipelineStageEvent> fireVisibleList;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final VerifysFormulaService formula;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final MedalsVisibilityService medalsVisibilityService;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final VerifyReadRepositoryGateway verifyReadRepositoryGateway;

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<Boolean> checkVisibility(Interaction prev, String uid) {
    Span startSpan = tracer.spanBuilder("verify-check-item-visbility").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return retrieveVisible(prev, uid).thenApply(Optional::isPresent).whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uids
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<Boolean> checkVisibility(Interaction prev, List<String> uids) {
    Span startSpan = tracer.spanBuilder("verify-check-item-visbility").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return listVisibles(prev, VerifyFilter.builder().uids(uids).build(),
          VerifyCursor.builder().build()).thenApply(list -> list.size() == uids.size())
              .whenComplete((val, ex) -> {
                if (null == ex) {
                  startSpan.setStatus(StatusCode.OK);
                } else {
                  startSpan.recordException(ex).setStatus(StatusCode.ERROR);
                }
                startSpan.end();
              });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param original The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<VerifyDto> copyWithFixed(Interaction prev, Verify original,
      VerifyDto source) {
    Span startSpan = tracer.spanBuilder("verify-copy-existent-with-fixed").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return visiblesReferences(prev, source)
          .thenCompose(dto -> fieldsToFix(prev, original).thenApply(fixeds -> {
            fixeds.forEach(field -> dto.fixField(field, original));
            return dto;
          })).thenCompose(fixed -> formula.copyWithFormulas(prev, original, fixed))
          .whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<VerifyDto> copyWithFixed(Interaction prev, VerifyDto source) {
    Span startSpan = tracer.spanBuilder("verify-copy-new-with-fixed").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return visiblesReferences(prev, source)
          .thenCompose(dto -> fieldsToFix(prev).thenApply(fixeds -> {
            fixeds.forEach(field -> dto.fixField(field));
            return dto;
          })).thenCompose(fixed -> formula.copyWithFormulas(prev, fixed))
          .whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param verify
   * @return The input dto with hidden values
   */
  public CompletionStage<VerifyDto> copyWithHidden(Interaction prev, Verify verify) {
    Span startSpan = tracer.spanBuilder("verify-copy-with-hidden").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return fieldsToHide(prev, verify).thenApply(hidden -> {
        VerifyDto target = VerifyDto.from(verify);
        hidden.forEach(target::hideField);
        return target;
      }).whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsFixFields
   */
  public CompletionStage<Set<String>> fieldsToFix(Interaction prev) {
    Span startSpan = tracer.spanBuilder("verify-field-to-fix-for-new").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      CompletionStage<Set<String>> fields = fieldsToHide(prev).thenApply(hidden -> {
        Set<String> set = new HashSet<>(aggregate.calcultadFields());
        set.addAll(hidden);
        return set;
      });
      VerifyFixedFieldsPipelineStageEvent value =
          VerifyFixedFieldsPipelineStageEvent.builder().fixed(fields).interaction(prev).build();
      fireFix.fire(value);
      return value.getFixed().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setAttribute("fieds", String.join(",", val));
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param verify
   * @return initialsFixFields
   */
  public CompletionStage<Set<String>> fieldsToFix(Interaction prev, VerifyRef verify) {
    Span startSpan = tracer.spanBuilder("verify-field-to-fix-for-existent").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      CompletionStage<Set<String>> fields =
          fieldsToFix(prev).thenCombine(fieldsToHide(prev, verify), (set1, set2) -> {
            Set<String> set = new HashSet<>(set1);
            set.addAll(set2);
            return set;
          });
      VerifyFixedFieldsPipelineStageEvent value = VerifyFixedFieldsPipelineStageEvent.builder()
          .fixed(fields).verify(verify).interaction(prev).build();
      fireFix.fire(value);
      return value.getFixed().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setAttribute("fieds", String.join(",", val));
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsHideFields
   */
  public CompletionStage<Set<String>> fieldsToHide(Interaction prev) {
    Span startSpan = tracer.spanBuilder("verify-field-to-hide-for-new").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      CompletionStage<Set<String>> fields = CompletableFuture.completedFuture(Set.of());
      VerifyHiddenFieldsPipelineStageEvent value =
          VerifyHiddenFieldsPipelineStageEvent.builder().hidden(fields).interaction(prev).build();
      fireHide.fire(value);
      return value.getHidden().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setAttribute("fieds", String.join(",", val));
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param verify
   * @return initialsHideFields
   */
  public CompletionStage<Set<String>> fieldsToHide(Interaction prev, VerifyRef verify) {
    Span startSpan = tracer.spanBuilder("verify-field-to-hide-for-existent").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      CompletionStage<Set<String>> fields = fieldsToHide(prev);
      VerifyHiddenFieldsPipelineStageEvent value = VerifyHiddenFieldsPipelineStageEvent.builder()
          .hidden(fields).verify(verify).interaction(prev).build();
      fireHide.fire(value);
      return value.getHidden().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setAttribute("fieds", String.join(",", val));
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<VerifyCached> listCachedVisibles(Interaction prev, VerifyFilter filter,
      VerifyCursor cursor) {
    Span startSpan = tracer.spanBuilder("verify-list-cached-visible").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return applyPreVisibilityFilter(prev, filter)
          .thenCompose(visfilter -> cache.retrieve(visfilter, cursor).thenCompose(cached -> {
            if (cached.isPresent()) {
              startSpan.setAttribute("source", "cache");
              return CompletableFuture.completedStage(cached.get());
            } else {
              startSpan.setAttribute("source", "gateway");
              return queryItems(prev, filter, cursor).thenApply(values -> {
                cache.store(filter, cursor, values);
                return VerifyCached.builder().value(values).since(OffsetDateTime.now()).build();
              });
            }
          })).whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<List<Verify>> listVisibles(Interaction prev, VerifyFilter filter,
      VerifyCursor cursor) {
    Span startSpan = tracer.spanBuilder("verify-list-visibles").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return applyPreVisibilityFilter(prev, filter)
          .thenCompose(visfilter -> queryItems(prev, visfilter, cursor)).whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<VerifyCached> retrieveCachedVisible(Interaction prev, String uid) {
    Span startSpan = tracer.spanBuilder("verify-retrieve-cached-visible").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return applyPreVisibilityFilter(prev, VerifyFilter.builder().uid(uid).build())
          .thenCompose(filter -> {
            filter.setUid(uid);
            VerifyCursor cursor = VerifyCursor.builder().limit(1).build();
            return cache.retrieve(filter, cursor).thenCompose(cached -> {
              if (cached.isPresent()) {
                startSpan.setAttribute("source", "cache");
                return CompletableFuture.completedStage(cached.get());
              } else {
                startSpan.setAttribute("source", "gateway");
                return queryItem(prev, uid, filter).thenApply(value -> {
                  List<Verify> values = value.map(List::of).orElseGet(List::of);
                  cache.store(filter, cursor, values);
                  return VerifyCached.builder().value(values).since(OffsetDateTime.now()).build();
                });
              }
            });
          }).whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public CompletionStage<Optional<Verify>> retrieveVisible(Interaction prev, String uid) {
    Span startSpan = tracer.spanBuilder("verify-retrieve-visible").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return applyPreVisibilityFilter(prev, VerifyFilter.builder().uid(uid).build())
          .thenCompose(filter -> queryItem(prev, uid, filter)).whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The self filter modified with the prepared values.
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @return The self filter modified with the prepared values.
   */
  private CompletionStage<VerifyFilter> applyPreVisibilityFilter(Interaction prev,
      VerifyFilter filter) {
    Span startSpan = tracer.spanBuilder("verify-calculate-visible-filter").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      VerifyVisibilityQueryPipelineStageEvent visible = VerifyVisibilityQueryPipelineStageEvent
          .builder().filter(CompletableFuture.completedFuture(filter)).interaction(prev).build();
      fireVisibleFilter.fire(visible);
      return visible.getFilter().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param verifyRefs The source interaction
   * @return The input dto with hidden values
   */
  private CompletionStage<List<Verify>> evaluatePostVisibility(Interaction prev,
      List<Verify> verifyRefs) {
    Span startSpan = tracer.spanBuilder("verify-evaluate-liste-post-visibility").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      VerifyVisibleContentPipelineStageEvent list = VerifyVisibleContentPipelineStageEvent.builder()
          .visibles(CompletableFuture.completedFuture(new ArrayList<>(verifyRefs)))
          .interaction(prev).build();
      fireVisibleList.fire(list);
      return list.getVisibles().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param verifyRef The source interaction
   * @return The input dto with hidden values
   */
  private CompletionStage<Optional<Verify>> evaluatePostVisibility(Interaction prev,
      Verify verifyRef) {
    Span startSpan = tracer.spanBuilder("verify-evaluate-item-post-visibility").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return evaluatePostVisibility(prev, List.of(verifyRef))
          .thenApply(list -> list.isEmpty() ? Optional.<Verify>empty() : Optional.of(list.get(0)))
          .whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private CompletionStage<Optional<Verify>> queryItem(Interaction prev, String uid,
      VerifyFilter filter) {
    Span startSpan = tracer.spanBuilder("verify-query-item").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return verifyReadRepositoryGateway.retrieve(uid, Optional.of(filter))
          .thenCompose(stored -> stored.map(retrieved -> evaluatePostVisibility(prev, retrieved))
              .orElseGet(() -> CompletableFuture.completedStage(Optional.empty())))
          .whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private CompletionStage<List<Verify>> queryItems(Interaction prev, VerifyFilter filter,
      VerifyCursor cursor) {
    Span startSpan = tracer.spanBuilder("verify-query-items").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return verifyReadRepositoryGateway.list(filter, cursor)
          .thenCompose(
              slide -> slide.filterAndFillAgain(values -> evaluatePostVisibility(prev, values)))
          .whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  private CompletionStage<VerifyDto> visiblesReferences(Interaction prev, VerifyDto source) {
    Span startSpan = tracer.spanBuilder("verify-visibles-reference").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      List<CompletionStage<Boolean>> related = new ArrayList<>();
      visiblesReferencesFromMedals(related, prev, source);
      return CompletableFuture.allOf(related.toArray(new CompletableFuture[0]))
          .thenApply(_void -> source).whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param related
   * @param prev The source interaction
   * @param source The source interaction
   */
  private void visiblesReferencesFromMedals(List<CompletionStage<Boolean>> related,
      Interaction prev, VerifyDto source) {
    if (null != source.getMedals()) {
      List<String> collectMedal = new ArrayList<>();
      source.getMedals().getValue().forEach(item -> {
        if (null != item.getMedal()) {
          String idMedal = item.getMedalReferenceValue();
          if (!collectMedal.contains(idMedal)) {
            collectMedal.add(idMedal);
          }
        }
      });
      related.add(medalsVisibilityService.checkVisibility(prev, collectMedal)
          .whenComplete((visible, fail) -> {
            if (!visible) {
              throw new NotFoundException("No all medal exists: " + collectMedal);
            }
          }));
    }
  }
}
