package org.acme.features.market.area.application.policy;

import org.acme.common.security.Actor;
import org.acme.features.market.area.application.service.proposal.AreaVisibilityQueryProposal;

import jakarta.enterprise.event.Observes;

public class MerchantAccesible {

  /**
   * Constant for rOOT field
   *
   * @autogenerated VisibilityPolicyGenerator
   */
  private static final String ROL_ROOT = "ROOT";

  /**
   * @autogenerated VisibilityPolicyGenerator
   * @param filter
   */
  public void filterVisibles(@Observes AreaVisibilityQueryProposal filter) {
    Actor actor = filter.getInteraction().getActor();
    if (!actor.hasRole(ROL_ROOT)) {
      filter.peek(fl -> fl.setPlaceMerchantMerchantAccesible(actor.getTenant().orElse(null)));
    }
  }
}
