package org.acme.features.market.color.application.usecase.retrieve;

import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotAllowedException;
import org.acme.common.security.Allow;
import org.acme.features.market.color.application.service.ColorsVisibilityService;
import org.acme.features.market.color.application.usecase.retrieve.event.ColorRetrieveAllowPipelineStageEvent;
import org.acme.features.market.color.domain.gateway.ColorCached;
import org.acme.features.market.color.domain.model.ColorRef;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.StatusCode;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Scope;
import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class RetrieveColorUsecase {

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated ListUsecaseGenerator
   */
  private final Event<ColorRetrieveAllowPipelineStageEvent> retrieveAllow;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final ColorsVisibilityService visibility;

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public CompletionStage<Allow> allow(final Interaction query, final ColorRef reference) {
    Span startSpan = tracer.spanBuilder("color-specific-allow-retrieve").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      ColorRetrieveAllowPipelineStageEvent base = ColorRetrieveAllowPipelineStageEvent.build(query,
          Optional.of(reference), true, "Allowed by default");
      retrieveAllow.fire(base);
      return base.getDetail().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setAttribute("allowed", val.isAllowed());
          startSpan.setAttribute("reason", val.getDescription());
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @return
   */
  public CompletionStage<Allow> allow(final Interaction query) {
    Span startSpan = tracer.spanBuilder("color-generic-allow-retrieve").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      ColorRetrieveAllowPipelineStageEvent base = ColorRetrieveAllowPipelineStageEvent.build(query,
          Optional.empty(), true, "Allowed by default");
      retrieveAllow.fire(base);
      return base.getDetail().whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setAttribute("allowed", val.isAllowed());
          startSpan.setAttribute("reason", val.getDescription());
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public CompletionStage<ColorRetrieveResult> retrieve(final ColorRetrieveQuery query) {
    Span startSpan = tracer.spanBuilder("color-retrieve").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      CompletionStage<ColorCached> result =
          allow(query, query.getReference()).thenCompose(detail -> {
            if (!detail.isAllowed()) {
              throw new NotAllowedException(detail.getDescription());
            }
            return visibility.retrieveCachedVisible(query, query.getReference().getUidValue());
          });
      return result.thenCompose(op -> this.mapEntity(query, op)).whenComplete((val, ex) -> {
        if (null == ex) {
          startSpan.setStatus(StatusCode.OK);
        } else {
          startSpan.recordException(ex).setStatus(StatusCode.ERROR);
        }
        startSpan.end();
      });
    }
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @param opcolor
   * @return The slide with some values
   */
  private CompletionStage<ColorRetrieveResult> mapEntity(final ColorRetrieveQuery query,
      final ColorCached opcolor) {
    Span startSpan = tracer.spanBuilder("color-map-retrieve-result").startSpan();
    try (Scope scope = startSpan.makeCurrent()) {
      return opcolor.first()
          .map(color -> visibility.copyWithHidden(query, color)
              .thenApply(colorWithHidden -> ColorRetrieveResult.builder().interaction(query)
                  .color(Optional.of(colorWithHidden)).since(opcolor.getSince()).build()))
          .orElseGet(() -> CompletableFuture.completedFuture(ColorRetrieveResult.builder()
              .interaction(query).color(Optional.empty()).since(OffsetDateTime.now()).build()))
          .whenComplete((val, ex) -> {
            if (null == ex) {
              startSpan.setStatus(StatusCode.OK);
            } else {
              startSpan.recordException(ex).setStatus(StatusCode.ERROR);
            }
            startSpan.end();
          });
    }
  }
}
