package org.acme.features.market.color.application.usecase.retrieve;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotAllowedException;
import org.acme.features.market.color.application.ColorDto;
import org.acme.features.market.color.application.service.ColorsVisibilityService;
import org.acme.features.market.color.domain.model.Color;
import org.acme.features.market.color.domain.model.ColorRef;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class RetrieveColorUsecase {

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated ListUsecaseGenerator
   */
  private final Event<ColorRetrieveAllow> retrieveAllow;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final ColorsVisibilityService visibility;

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public ColorRetrieveAllow allow(final Interaction query, final ColorRef reference) {
    ColorRetrieveAllow base =
        ColorRetrieveAllow.build(query, Optional.of(reference), true, "Allowed by default");
    retrieveAllow.fire(base);
    return base;
  }

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @return
   */
  public ColorRetrieveAllow allow(final Interaction query) {
    ColorRetrieveAllow base =
        ColorRetrieveAllow.build(query, Optional.empty(), true, "Allowed by default");
    retrieveAllow.fire(base);
    return base;
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public ColorRetrieveResult retrieve(final ColorRetrieveQuery query) {
    CompletionStage<Optional<Color>> result =
        allow(query, query.getReference()).getDetail().thenCompose(detail -> {
          if (!detail.isAllowed()) {
            throw new NotAllowedException(detail.getDescription());
          }
          return visibility.retrieveVisible(query, query.getReference().getUidValue());
        });
    return ColorRetrieveResult.builder().interaction(query)
        .color(result.thenCompose(op -> this.mapEntity(query, op))).build();
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @param opcolor
   * @return The slide with some values
   */
  private CompletionStage<Optional<ColorDto>> mapEntity(final ColorRetrieveQuery query,
      final Optional<Color> opcolor) {
    return opcolor.map(color -> visibility.copyWithHidden(query, color).thenApply(Optional::of))
        .orElseGet(() -> CompletableFuture.completedFuture(Optional.empty()));
  }
}
