package org.acme.features.market.place.application.interaction.command;

import org.acme.common.action.Interaction;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class PlacePhotoTemporalUploadReadCommand extends Interaction {

  /**
   * @autogenerated EntityGenerator
   */
  @NonNull
  private String key;
}
