package org.acme.features.market.color.application.service.event;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.function.Consumer;

import org.acme.common.action.Interaction;
import org.acme.features.market.color.application.ColorDto;
import org.acme.features.market.color.domain.model.Color;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class ColorFormulaBuilderPipelineStageEvent {

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   */
  @NonNull
  private CompletionStage<ColorDto> dto;

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   */
  private Color original;

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   * @return
   */
  public Optional<Color> getOriginal() {
    return Optional.ofNullable(original);
  }

  /**
   * @autogenerated FormulaBuilderPipelineStageEventGenerator
   * @param mapper
   */
  public void tap(Consumer<ColorDto> mapper) {
    dto = dto.thenApply(dto -> {
      mapper.accept(dto);
      return dto;
    });
  }
}
