package org.acme.features.market.color.application.service.event;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.function.Consumer;

import org.acme.common.action.Interaction;
import org.acme.features.market.color.application.ColorDto;
import org.acme.features.market.color.domain.model.Color;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class ColorFormulaBuilder extends Interaction {

  /**
   * @autogenerated VisibleContentGenerator
   */
  Color original;

  /**
   * @autogenerated VisibleContentGenerator
   */
  @NonNull
  private CompletionStage<ColorDto> dto;

  /**
   * @autogenerated VisibleContentGenerator
   * @return
   */
  public Optional<Color> getOriginal() {
    return Optional.ofNullable(original);
  }

  /**
   * @autogenerated VisibleContentGenerator
   * @param mapper
   */
  public void tap(Consumer<ColorDto> mapper) {
    dto = dto.thenApply(dto -> {
      mapper.accept(dto);
      return dto;
    });
  }
}
