package org.acme.features.market.fruit.domain;

import org.acme.features.market.fruit.domain.interaction.result.ListResult;
import org.acme.features.market.fruit.domain.interaction.result.RetrieveResult;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class FruitsEvent {

  /**
   * Event bus for list result events
   *
   * @autogenerated ListTraitGenerator
   */
  private final Event<ListResult> listResultEventBus;

  /**
   * Event bus for individual result events
   *
   * @autogenerated ListTraitGenerator
   */
  private final Event<RetrieveResult> resultEventBus;

  /**
   * The param modified after
   *
   * @autogenerated ListTraitGenerator
   * @param event The result event
   * @return The param modified after
   */
  public ListResult fireFruitListResult(final ListResult event) {
    listResultEventBus.fire(event);
    return event;
  }

  /**
   * The param modified after
   *
   * @autogenerated ListTraitGenerator
   * @param event The result event
   * @return The param modified after
   */
  public RetrieveResult fireFruitRetrieveResult(final RetrieveResult event) {
    resultEventBus.fire(event);
    return event;
  }
}
