package org.acme.features.market.place.application.usecase.update;

import org.acme.common.action.Interaction;
import org.acme.features.market.place.application.PlaceDto;
import org.acme.features.market.place.application.service.proposal.PlaceModifyProposal;
import org.acme.features.market.place.domain.model.Place;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class PlaceUpdateProposal extends PlaceModifyProposal {

  /**
   * @autogenerated UpdateProposalGenerator
   * @param emitter
   * @param interaction
   * @param dto
   * @param entity
   * @return
   */
  public static PlaceDto resolveWith(final Event<PlaceUpdateProposal> emitter,
      final Interaction interaction, final PlaceDto dto, final Place entity) {
    return resolveWith(emitter,
        PlaceUpdateProposal.builder().interaction(interaction).dto(dto).entity(entity).build());
  }
}
