package org.acme.features.market.merchant.application.service.event;

import java.util.List;
import java.util.concurrent.CompletionStage;

import org.acme.common.action.Interaction;
import org.acme.features.market.merchant.domain.model.Merchant;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class MerchantVisibleContent extends Interaction {

  /**
   * @autogenerated VisibleContentGenerator
   */
  @NonNull
  private CompletionStage<List<Merchant>> visibles;
}
