package org.acme.features.market.merchant.application.usecase.enable;

import org.acme.common.action.Interaction;
import org.acme.features.market.merchant.application.service.event.MerchantEntityEvent;
import org.acme.features.market.merchant.domain.model.Merchant;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class MerchantEnableEvent extends MerchantEntityEvent {

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @param emitter
   * @param interaction
   * @param entity
   */
  @SuppressWarnings("unchecked")
  public static void notifyWith(final Event<? extends MerchantEnableEvent> emitter,
      final Interaction interaction, final Merchant entity) {
    ((Event<MerchantEnableEvent>) emitter)
        .fire(MerchantEnableEvent.builder().interaction(interaction).entity(entity).build());
  }

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @return
   */
  @Override
  public String operation() {
    return "enable";
  }
}
