package org.acme.features.market.fruit.application.interaction.visibility;

import java.util.Optional;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

import org.acme.common.action.Interaction;
import org.acme.features.market.fruit.domain.model.FruitRef;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

@Getter
@ToString
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class FruitHiddenFields extends Interaction {

  /**
   * @autogenerated HiddenFieldsGenerator
   */
  private FruitRef fruit;

  /**
   * The list of hidden fields
   *
   * @autogenerated HiddenFieldsGenerator
   */
  @NonNull
  private CompletableFuture<Set<String>> hidden;

  /**
   * @autogenerated HiddenFieldsGenerator
   * @return
   */
  public Optional<FruitRef> getFruit() {
    return Optional.ofNullable(fruit);
  }
}
