package org.acme.features.market.medal.application.usecase.update;

import org.acme.common.action.Interaction;
import org.acme.features.market.medal.application.MedalDto;
import org.acme.features.market.medal.application.service.proposal.MedalModifyProposal;
import org.acme.features.market.medal.domain.model.Medal;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class MedalUpdateProposal extends MedalModifyProposal {

  /**
   * @autogenerated UpdateProposalGenerator
   * @param emitter
   * @param interaction
   * @param dto
   * @param entity
   * @return
   */
  public static MedalDto resolveWith(final Event<MedalUpdateProposal> emitter,
      final Interaction interaction, final MedalDto dto, final Medal entity) {
    return resolveWith(emitter,
        MedalUpdateProposal.builder().interaction(interaction).dto(dto).entity(entity).build());
  }
}
