package org.acme.features.market.medal.application.usecase.update;

import java.util.Optional;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotAllowedException;
import org.acme.common.exception.NotFoundException;
import org.acme.common.security.Allow;
import org.acme.features.market.medal.application.MedalDto;
import org.acme.features.market.medal.application.service.MedalsVisibilityService;
import org.acme.features.market.medal.domain.Medals;
import org.acme.features.market.medal.domain.gateway.MedalCacheGateway;
import org.acme.features.market.medal.domain.gateway.MedalWriteRepositoryGateway;
import org.acme.features.market.medal.domain.model.Medal;
import org.acme.features.market.medal.domain.model.MedalRef;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class UpdateMedalUsecase {

  /**
   * @autogenerated UpdateUsecaseGenerator
   */
  private final Medals aggregate;

  /**
   * @autogenerated UpdateUsecaseGenerator
   */
  private final MedalCacheGateway cache;

  /**
   * @autogenerated UpdateUsecaseGenerator
   */
  private final MedalWriteRepositoryGateway gateway;

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated UpdateUsecaseGenerator
   */
  private final Event<MedalUpdateAllowPipelineEvent> updateAllow;

  /**
   * @autogenerated UpdateUsecaseGenerator
   */
  private final MedalsVisibilityService visibility;

  /**
   * @autogenerated UpdateUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public Allow allow(final Interaction query, final MedalRef reference) {
    MedalUpdateAllowPipelineEvent base = MedalUpdateAllowPipelineEvent.build(query,
        Optional.of(reference), true, "Allowed by default");
    updateAllow.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated UpdateUsecaseGenerator
   * @param query
   * @return
   */
  public Allow allow(final Interaction query) {
    MedalUpdateAllowPipelineEvent base =
        MedalUpdateAllowPipelineEvent.build(query, Optional.empty(), true, "Allowed by default");
    updateAllow.fire(base);
    return base.getDetail();
  }

  /**
   * The slide with some values
   *
   * @autogenerated UpdateUsecaseGenerator
   * @param command a filter to retrieve only matching values
   * @return The slide with some values
   */
  public MedalDto update(final MedalUpdateCommand command) {
    Allow detail = allow(command, command.getReference());
    if (!detail.isAllowed()) {
      throw new NotAllowedException(detail.getDescription());
    }
    MedalDto dto = visibility.copyWithFixed(command, command.getDto());
    Medal original = visibility.retrieveVisible(command, command.getReference().getUidValue())
        .orElseThrow(() -> new NotFoundException(""));
    Medal saved = gateway.update(original,
        aggregate.modify(original, dto.toEntityBuilder(Optional.of(original))));
    cache.update(saved);
    return visibility.copyWithHidden(command, saved);
  }
}
