package org.acme.features.market.merchant.domain.model.rule;

import java.util.Iterator;

import org.acme.features.market.merchant.domain.model.Merchant;

public interface MerchantCreateRulePipeline {

  /**
   * @autogenerated AggregateGenerator
   * @param rules
   * @param merchant
   * @return
   */
  public static Merchant fire(Iterator<MerchantCreateRulePipeline> rules, Merchant merchant) {
    Merchant result = merchant;
    while (rules.hasNext()) {
      result = rules.next().creating(result);
    }
    return result;
  }

  /**
   * @autogenerated AggregateGenerator
   * @param merchant
   * @return
   */
  Merchant creating(Merchant merchant);
}
