/* @autogenerated */
package org.acme.common.connector;

import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

public interface RemoteQuery {

  RemoteQuery header(String name, String value);

  RemoteQuery header(String name, List<String> values);

  RemoteQuery headers(Map<String, List<String>> headers);

  RemoteQuery queryParam(String name, String value);

  RemoteQuery queryParam(Map<String, String> params);

  RemoteQuery pathParam(String name, String value);

  RemoteQuery pathParam(Map<String, String> params);

  <T> RemoteConnection processor(Class<T> type, Consumer<T> consumer);

  RemoteConnection processor(Runnable runnable);
}
