package org.acme.features.market.color.application.policy;

import org.acme.common.security.Actor;
import org.acme.features.market.color.application.service.event.ColorFormulaBuilderPipelineEvent;
import org.acme.features.market.color.domain.model.valueobject.ColorMerchantVO;

import jakarta.enterprise.event.Observes;

public class HeritageMerchant {

  /**
   * Constant for rOOT field
   *
   * @autogenerated FormulaRuleGenerator
   */
  private static final String ROL_ROOT = "ROOT";

  /**
   * @autogenerated FormulaRuleGenerator
   * @param builder
   */
  public void calculate(@Observes ColorFormulaBuilderPipelineEvent builder) {
    Actor actor = builder.getInteraction().getActor();
    if (!actor.hasRole(ROL_ROOT)) {
      builder.peek(
          dto -> dto.setMerchant(ColorMerchantVO.tryFromReference(actor.getTenant().orElse(null))));
    }
  }
}
