package org.acme.features.market.place.application.usecase.delete;

import org.acme.common.action.Interaction;
import org.acme.features.market.place.application.service.event.PlaceEntityEvent;
import org.acme.features.market.place.domain.model.Place;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class PlaceDeleteEvent extends PlaceEntityEvent {

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @param emitter
   * @param interaction
   * @param entity
   */
  @SuppressWarnings("unchecked")
  public static void notifyWith(final Event<? extends PlaceDeleteEvent> emitter,
      final Interaction interaction, final Place entity) {
    ((Event<PlaceDeleteEvent>) emitter)
        .fire(PlaceDeleteEvent.builder().interaction(interaction).entity(entity).build());
  }

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @return
   */
  @Override
  public String operation() {
    return "delete";
  }
}
