package org.acme.features.market.place.application.service;

import org.acme.common.action.Interaction;
import org.acme.features.market.place.application.PlaceDto;
import org.acme.features.market.place.application.service.proposal.PlaceCalculatedProposal;
import org.acme.features.market.place.domain.model.Place;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class PlacesCalculatorService {

  /**
   * Event source for maniputale the visible list
   *
   * @autogenerated CalculatorServiceGenerator
   */
  private final Event<PlaceCalculatedProposal> formulaBuilder;

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated CalculatorServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @param original The source interaction
   * @return The input entity with the copy values without hidden
   */
  public PlaceDto copyWithFormulas(Interaction prev, PlaceDto source, Place original) {
    PlaceCalculatedProposal formulas =
        PlaceCalculatedProposal.builder().dto(source).original(original).interaction(prev).build();
    formulaBuilder.fire(formulas);
    return formulas.getDto();
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated CalculatorServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public PlaceDto copyWithFormulas(Interaction prev, PlaceDto source) {
    PlaceCalculatedProposal formulas =
        PlaceCalculatedProposal.builder().dto(source).interaction(prev).build();
    formulaBuilder.fire(formulas);
    return formulas.getDto();
  }
}
