package org.acme.features.market.area.application.service.event;

import org.acme.common.action.Interaction;
import org.acme.features.market.area.domain.model.Area;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class AreaVisibleContentPipelineEvent {

  /**
   * @autogenerated VisibleContentPipelineEventGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated VisibleContentPipelineEventGenerator
   */
  @NonNull
  private Area entity;

  /**
   * @autogenerated VisibleContentPipelineEventGenerator
   */
  @NonNull
  private Boolean visible;
}
