package org.acme.features.market.area.application.service.event;

import org.acme.common.action.Interaction;
import org.acme.features.market.area.domain.model.Area;

import jakarta.enterprise.event.Event;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public abstract class AreaEntityEvent {

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @param emitter
   * @param event
   */
  @SuppressWarnings("unchecked")
  public static void notifyWith(final Event<? extends AreaEntityEvent> emitter,
      final AreaEntityEvent event) {
    ((Event<AreaEntityEvent>) emitter).fire(event);
  }

  /**
   * @autogenerated VisibleContentProposalGenerator
   */
  @NonNull
  private final Area entity;

  /**
   * @autogenerated VisibleContentProposalGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated VisibleContentProposalGenerator
   * @return
   */
  public abstract String operation();
}
