package org.acme.features.market.area.application.service.event;

import java.util.Optional;

import org.acme.common.security.PropertiesPipelineEvent;
import org.acme.features.market.area.domain.model.AreaRef;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class AreaHiddenFieldsPipelineEvent extends PropertiesPipelineEvent {

  /**
   * @autogenerated HiddenFieldsPipelineEventGenerator
   */
  private final AreaRef area;

  /**
   * @autogenerated HiddenFieldsPipelineEventGenerator
   * @return
   */
  public Optional<AreaRef> getArea() {
    return Optional.ofNullable(area);
  }

  /**
   * @autogenerated HiddenFieldsPipelineEventGenerator
   * @return
   */
  public String resourceName() {
    return "area";
  }

  /**
   * @autogenerated HiddenFieldsPipelineEventGenerator
   * @return
   */
  public String viewName() {
    return "view";
  }
}
