package org.acme.features.market.verify.application.usecase.retrieve;

import java.util.Optional;

import org.acme.common.action.Interaction;
import org.acme.common.exception.NotAllowedException;
import org.acme.common.exception.NotFoundException;
import org.acme.common.security.Allow;
import org.acme.features.market.verify.application.VerifyDto;
import org.acme.features.market.verify.application.service.VerifysVisibilityService;
import org.acme.features.market.verify.domain.gateway.VerifyCached;
import org.acme.features.market.verify.domain.model.VerifyRef;

import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;

@RequestScoped
@RequiredArgsConstructor
public class RetrieveVerifyUsecase {

  /**
   * Event source for maniputale the visibility filter over the entity fields
   *
   * @autogenerated ListUsecaseGenerator
   */
  private final Event<VerifyRetrieveAllowProposal> retrieveAllow;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final VerifysVisibilityService visibility;

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public Allow allow(final Interaction query, final VerifyRef reference) {
    VerifyRetrieveAllowProposal base = VerifyRetrieveAllowProposal.build(query,
        Optional.of(reference), true, "Allowed by default");
    retrieveAllow.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated ListUsecaseGenerator
   * @param query
   * @return
   */
  public Allow allow(final Interaction query) {
    VerifyRetrieveAllowProposal base =
        VerifyRetrieveAllowProposal.build(query, Optional.empty(), true, "Allowed by default");
    retrieveAllow.fire(base);
    return base.getDetail();
  }

  /**
   * The slide with some values
   *
   * @autogenerated ListUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public VerifyDto retrieve(final VerifyRetrieveQuery query) {
    Allow detail = allow(query, query.getReference());
    if (!detail.isAllowed()) {
      throw new NotAllowedException(detail.getDescription());
    }
    VerifyCached retrieveCachedVisible =
        visibility.retrieveCachedVisible(query, query.getReference().getUidValue());
    return retrieveCachedVisible.first().map(first -> visibility.copyWithHidden(query, first))
        .orElseThrow(() -> new NotFoundException(""));
  }
}
